name: luping
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  get: ^4.6.5
  flutter_svg: ^1.1.0
  shimmer: ^3.0.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.5
  animations: ^2.0.11
  flutter_html: ^3.0.0-beta.2
  http: ^1.3.0

  audioplayers: ^5.2.1
  just_audio: ^0.9.46
  logger: ^2.0.2

  flutter_dotenv: ^5.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  flutter_staggered_grid_view: ^0.7.0
  rxdart: ^0.28.0
  flutter_sound: ^9.23.1
  ffmpeg_kit_flutter: ^6.0.3
  permission_handler: ^11.4.0
  change_app_package_name: ^1.5.0
dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  sqflite_common_ffi: ^2.3.2

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lib/data/HanziStory.sqlite
    - .env

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf

flutter_launcher_icons:
  image_path: "assets/logo.png" # Path to your app icon
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # Default is 48
  macos:
    generate: true
    image_path: "assets/logo.png"