name: hanjii
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  get: ^4.6.5
  flutter_svg: ^1.1.0
  shimmer: ^3.0.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.5
  animations: ^2.0.11
  flutter_html: ^3.0.0-beta.2
  http: ^1.3.0

  audioplayers: ^6.1.2
  just_audio: ^0.9.46
  logger: ^2.0.2

  flutter_dotenv: ^5.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  flutter_staggered_grid_view: ^0.7.0
  rxdart: ^0.28.0
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  sqflite_common_ffi: ^2.3.2

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lib/data/HanziStory.sqlite
    - .env

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
