server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "nodejs-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "nodejs-app"
          source: "combined"
          __path__: "/var/log/combined.log"

      - targets:
          - localhost
        labels:
          job: "nodejs-app"
          source: "errors"
          __path__: "/var/log/errors.log"
